services:
  - type: web
    name: mysocial
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn socialmedia.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: socialmedia.settings
      - key: SECRET_KEY
        value: '+=o*18o+but41i#jgi#^wy%bihj29%dxdj@nnxrmrwb*ftc=$@'
      - key: DEBUG
        value: False
